apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-sponsorship-landing-page
  namespace: tm-sponsorship-landing-page
  labels:
    app: tm-sponsorship-landing-page
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: tm-sponsorship-landing-page
  template:
    metadata:
      labels:
        app: tm-sponsorship-landing-page
    spec:
      imagePullSecrets:
        - name: acr-json-key
      containers:
        - name: tm-sponsorship-landing-page
          image: acrtmappprodcentralus.azurecr.io/tm-app/tm-sponsorship-landing-page:main-0480f94
          ports:
            - containerPort: 3000 
          resources:
            requests:
              memory: "256Mi" 
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
