apiVersion: v1
kind: Service
metadata:
  name: tm-sponsorship-landing-page-service
  namespace: tm-sponsorship-landing-page
spec:
  selector:
    app: tm-sponsorship-landing-page
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 3000  
  type: ClusterIP  
